### ISSUE TITLE
[Investigation request] - Migrate to react query 

### ISSUE THREAD

**Issue by KuhArt** [paralect/react-starter#90]
Maybe the time has come to migrate to the to react query library from the redux approach. 
Please, could you provide the pros and cons of the new hooks solution. 
And if the to react query is better, please, create the plan for migration.

**Comment by Oigen43** [comment]
@KuhArt  I think we need to update our state management logic even if we continue to use Redux

In case using Redux we need to do 2 things.

1. Add [Reselect](https://github.com/reduxjs/reselect) library.
It's library for creating memoizing selectors, because know dispatching any action will cause to unnecessary rerenders.
Good description why we need it from Redux Doc. [link](https://redux.js.org/tutorials/essentials/part-6-performance-normalization#memoizing-selector-functions)

2. Use Redux Toolkit
Redux Team launched Redux Toolkit, an officially recommended.
This is the recommended way to work with Redux, and it reduces the number of boilerplate
[Description](https://redux-toolkit.js.org/introduction/getting-started)
It's also include reselect library.

**Comment by AllDayAlone** [comment]
From my experience, it's an absolute winner. I can provide some examples from bluebanc projects. Here are some notes:

+ less boilerplate
+ more features out-of-box (cache, refetch, pagination, infinite list, suspense)
+ fewer opportunities to invent a bicycle
+ unified-style for request state (isLoading, isFetching, etc)
- I'm still not sure what to do with REAL GLOBAL state like "current user". It's still in redux in our project and it seems fine
- I'm still not sure what to do with not async data (like wizard state). I did local mini-redux for it.

**Comment by Oigen43** [comment]
@AllDayAlone I think we can wrap the app at the root level in UserContext

**Comment by Oigen43** [comment]
https://reactjs.org/docs/context.html#when-to-use-context
